import { atom } from 'jotai';

// Global atom to track the player's total progress across all screens
export const playerProgressAtom = atom({
  damage: 0,
  attackSpeed: 0,
  criticalChance: 0,
  criticalFactor: 0,
  attackRange: 0,
  damagePerMeter: 0,
  multishotChance: 0,
  multishotTargets: 0,
  rapidFireChance: 0,
  rapidFireDuration: 0,
  bounceShotChance: 0,
  bounceShotTargets: 0,
  bounceShotRange: 0,
  superCritChance: 0,
  superCritMult: 0,
  health: 0,
  healthRegen: 0,
  defensePercentage: 0,
  defenseAbsolute: 0,
  thornDamage: 0,
  lifesteal: 0,
  knockbackChance: 0,
  knockbackForce: 0,
  orbSpeed: 0,
  orbs: 0,
  shockwaveSize: 0,
  shockwaveFrequency: 0,
  landMineChance: 0,
  landMineDamage: 0,
  landMineRadius: 0,
  deathDefy: 0,
}); 